title: You finally arrived
description: >- 
  and other famous sentences to be dramatic
url: "https://yaphewill.github.io" 
baseurl: "" # Leave this empty for GitHub Pages

theme: jekyll-theme-hacker

# Author Information
author:
  name: "William"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
